version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /srv/app/node_modules
      - ./server:/srv/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /srv/app/node_modules
      - ./client:/srv/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
